import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Cpu } from "lucide-react";

export default function ArchitecturePage() {
  return (
    <div className="p-4 md:p-8 max-w-6xl mx-auto">
      <div className="mb-6">
        <h1 className="text-3xl font-bold">Architecture Maps</h1>
        <p className="text-muted-foreground mt-1">Interactive dependency graphs generated by the Architecture Agent.</p>
      </div>
      <Card className="bg-background/60 backdrop-blur-sm border-white/10 h-[600px] flex flex-col items-center justify-center text-center">
        <Cpu className="h-12 w-12 text-muted-foreground/50 mb-4" />
        <CardTitle className="text-xl">Dependency Graph Loading</CardTitle>
        <CardDescription className="max-w-md mt-2">
          The Architecture Mapping Agent is currently parsing the AST to generate module relationships.
          This will show an interactive Mermaid.js diagram.
        </CardDescription>
      </Card>
    </div>
  );
}
