import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Play, Activity, CheckCircle2, AlertTriangle, FileCode2 } from "lucide-react";

export default function RepoOverview() {
  return (
    <div className="p-4 md:p-8 max-w-6xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold">acme-corp / devkit-ai-saas</h1>
          <p className="text-muted-foreground mt-1">
            Last indexed 2 hours ago • 1.2M lines of TypeScript
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">View on GitHub</Button>
          <Button className="bg-primary">
            <Play className="mr-2 h-4 w-4" />
            Run Deep Analysis (300 Credits)
          </Button>
        </div>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-6">
          <Card className="bg-background/60 backdrop-blur-sm border-white/10">
            <CardHeader>
              <CardTitle>AI Analysis Summary</CardTitle>
              <CardDescription>Generated by RepoMind Agent</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-sm leading-relaxed text-muted-foreground">
              <p>
                This repository is a full-stack Next.js 16 application utilizing the App Router. 
                It functions as an AI SaaS platform with billing integrated via Stripe and authentication via Clerk.
              </p>
              <p>
                The backend relies on Prisma ORM connected to a MySQL database. State management is handled by Zustand and React Query. 
                The application heavily relies on the Vercel AI SDK for LLM interactions.
              </p>
              <div className="pt-4 border-t border-border/50">
                <h4 className="font-semibold text-foreground mb-2">Key Workflows Identified:</h4>
                <ul className="list-disc list-inside space-y-1">
                  <li>User Authentication & Session Management</li>
                  <li>Stripe Webhook Processing & Credit Deductions</li>
                  <li>RAG Pipeline (Document Upload → Parsing → Vector DB)</li>
                  <li>Real-time Agent Streaming</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-background/60 backdrop-blur-sm border-white/10">
            <CardHeader>
              <CardTitle>Recent Agent Activity</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {[
                  { task: "Initial Codebase Indexing", status: "Success", time: "2h ago", icon: CheckCircle2, color: "text-green-500" },
                  { task: "Security Audit Scan", status: "Warning", time: "2h ago", icon: AlertTriangle, color: "text-amber-500" },
                  { task: "Architecture Graph Generation", status: "Success", time: "3h ago", icon: CheckCircle2, color: "text-green-500" },
                ].map((item, i) => (
                  <div key={i} className="flex items-center gap-4 text-sm">
                    <item.icon className={`h-5 w-5 ${item.color}`} />
                    <div className="flex-1">
                      <p className="font-medium">{item.task}</p>
                      <p className="text-xs text-muted-foreground">{item.time}</p>
                    </div>
                    <Badge variant="outline">{item.status}</Badge>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card className="bg-background/60 backdrop-blur-sm border-white/10">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Activity className="h-5 w-5" />
                Index Health
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span>Files Parsed</span>
                  <span className="font-medium">1,402 / 1,402</span>
                </div>
                <Progress value={100} className="h-2 bg-secondary" />
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span>Vector Embeddings</span>
                  <span className="font-medium">8,240 Chunks</span>
                </div>
                <Progress value={100} className="h-2 bg-secondary" />
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span>AST Generation</span>
                  <span className="font-medium">Complete</span>
                </div>
                <Progress value={100} className="h-2 bg-secondary" />
              </div>
            </CardContent>
          </Card>

          <Card className="bg-background/60 backdrop-blur-sm border-white/10">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileCode2 className="h-5 w-5" />
                Tech Stack
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "Prisma", "BullMQ", "Pinecone", "Stripe"].map(tech => (
                  <Badge key={tech} variant="secondary" className="bg-primary/10 text-primary hover:bg-primary/20">
                    {tech}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

function Badge({ children, className, variant = "default" }: any) {
  return <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ${className}`}>{children}</span>
}
